// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivAplVb-ylD0vCu-8Jb0QVt4V-hYhtk0',
    appId: '1:604956694732:web:0074edd465c51ef1ce8a69',
    messagingSenderId: '604956694732',
    projectId: 'gym-app-66117',
    authDomain: 'gym-app-66117.firebaseapp.com',
    storageBucket: 'gym-app-66117.firebasestorage.app',
    measurementId: 'G-M042TDKVQB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaIexYGOTWT8eVGGhff8242AYFDeZ3x60',
    appId: '1:604956694732:ios:7a16e9dadf0aede8ce8a69',
    messagingSenderId: '604956694732',
    projectId: 'gym-app-66117',
    storageBucket: 'gym-app-66117.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaIexYGOTWT8eVGGhff8242AYFDeZ3x60',
    appId: '1:604956694732:ios:7a16e9dadf0aede8ce8a69',
    messagingSenderId: '604956694732',
    projectId: 'gym-app-66117',
    storageBucket: 'gym-app-66117.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDivAplVb-ylD0vCu-8Jb0QVt4V-hYhtk0',
    appId: '1:604956694732:web:0074edd465c51ef1ce8a69',
    messagingSenderId: '604956694732',
    projectId: 'gym-app-66117',
    authDomain: 'gym-app-66117.firebaseapp.com',
    storageBucket: 'gym-app-66117.firebasestorage.app',
    measurementId: 'G-M042TDKVQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb7EgRUEDFvKzTzTj1XLqpqCKNV_fJS3o',
    appId: '1:604956694732:android:21bc579d8bdceffbce8a69',
    messagingSenderId: '604956694732',
    projectId: 'gym-app-66117',
    storageBucket: 'gym-app-66117.firebasestorage.app',
  );

}