import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

import 'screens/login_screen.dart';
import 'screens/account_screen.dart'; // Make sure you import AccountScreen

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Get current user
    final user = FirebaseAuth.instance.currentUser;

    return MaterialApp(
      title: 'GYM App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      // Use initialRoute instead of home
      initialRoute: user == null ? '/login' : '/account',
      routes: {
        '/login': (context) => const LoginScreen(),
        '/account': (context) => const AccountScreen(),
      },
    );
  }
}
